%% This code rotates vector v (Cartesian vector) by angles thetax, thetay, thetaz about the x-axis, y-axis, and z-axis respectively 
% note that rotation in 3D is not commutative so check the definition of w and adjust the order of the rotation matrices if needed
close all
clear all
clc

%% original data
%generate random real numbers which should be replaced by the x, y, and z data values
xdata = randn(10,1);  %put your x coordinates here
ydata = randn(10,1);  %put your y coordinates here
zdata = randn(10,1);  %put your z coordinates here
figure(1)
scatter3(xdata,ydata,zdata,'filled')
hold on

%% rotation angles
thetax = 0; %angle (in degrees) by which you want to rotate v about the x-axis
thetay = 180;  %angle (in degrees) by which you want to rotate v about the y-axis
thetaz = 0;  %angle (in degrees) by which you want to rotate v about the z-axis

%% new data generated by rotation matrices
Rx = [1 0 0; 0 cosd(thetax) -sind(thetax); 0 sind(thetax) cosd(thetax)]; %R_x rotation matrix
Ry = [cosd(thetay) 0 sind(thetay); 0 1 0; -sind(thetay) 0 cosd(thetay)]; %R_y rotation matrix
Rz = [cosd(thetaz) -sind(thetaz) 0 ; sind(thetaz) cosd(thetaz) 0; 0 0 1];%R_z rotation matrix
rotateddata = zeros(length(xdata),1);
for n = 1:length(xdata)
v = transpose([xdata(n) ydata(n) zdata(n)]); %v is the original data point 
w = Rz*Ry*Rx*v; %this is the rotated data point
xdatar(n) = w(1); %xdatar is the rotated x-data
ydatar(n) = w(2); %ydatar is the rotated y-data
zdatar(n) = w(3); %zdatar is the rotated z-data
end

scatter3(xdatar,ydatar,zdata)
legend('original','rotated')
legend('Location','best')
xlabel('$x$','interpreter','latex')
ylabel('$y$','interpreter','latex')
zlabel('$z$','interpreter','latex')
